/**
 * Generates public/firebase-messaging-sw.js from frontend/.env Firebase vars.
 * Run: npm run fcm-sw
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

function loadEnv() {
  const env = {};
  for (const file of ['.env', '.env.local']) {
    try {
      const content = readFileSync(join(root, file), 'utf8');
      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const idx = trimmed.indexOf('=');
        if (idx === -1) continue;
        env[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
      }
    } catch {
      // optional file
    }
  }
  return env;
}

const env = { ...loadEnv(), ...process.env };
const required = [
  'VITE_FIREBASE_API_KEY',
  'VITE_FIREBASE_AUTH_DOMAIN',
  'VITE_FIREBASE_PROJECT_ID',
  'VITE_FIREBASE_STORAGE_BUCKET',
  'VITE_FIREBASE_MESSAGING_SENDER_ID',
  'VITE_FIREBASE_APP_ID',
];

const config = Object.fromEntries(required.map((key) => [key.replace('VITE_FIREBASE_', '').toLowerCase().replace(/_([a-z])/g, (_, c) => c.toUpperCase()), env[key] ?? '']));
const hasConfig = required.every((key) => Boolean(env[key]));

const sw = `/* Auto-generated by scripts/generate-fcm-sw.mjs — do not edit */
importScripts('https://www.gstatic.com/firebasejs/11.4.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/11.4.0/firebase-messaging-compat.js');

${hasConfig ? `firebase.initializeApp(${JSON.stringify({
  apiKey: env.VITE_FIREBASE_API_KEY,
  authDomain: env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: env.VITE_FIREBASE_APP_ID,
}, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || payload.data?.title || 'Pharma Exchange';
  const body = payload.notification?.body || payload.data?.body || '';
  const data = payload.data || {};
  self.registration.showNotification(title, {
    body,
    icon: '/icons/icon-192.png',
    badge: '/icons/icon-96.png',
    data,
    tag: data.orderId || data.conversationId || data.buyRequestId || 'pharmex',
  });
});` : '// Firebase not configured — background push disabled'}

function getNotificationPath(data) {
  if (!data) return '/';
  if (data.orderId) return '/orders/' + data.orderId;
  if (data.conversationId) return '/chat/' + data.conversationId;
  if (data.buyRequestId) return '/buy-requests/' + data.buyRequestId;
  if (data.listingId) return '/medicine/' + data.listingId;
  if (data.pharmacyId) return '/pharmacy/' + data.pharmacyId;
  return '/notifications';
}

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const path = getNotificationPath(event.notification.data);
  const url = new URL(path, self.location.origin).href;
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          return client.focus().then((focused) => {
            if ('navigate' in focused) return focused.navigate(url);
            return focused;
          });
        }
      }
      return clients.openWindow(url);
    }),
  );
});
`;

writeFileSync(join(root, 'public', 'firebase-messaging-sw.js'), sw);
console.log(hasConfig ? 'Generated firebase-messaging-sw.js with Firebase config' : 'Generated firebase-messaging-sw.js (Firebase not configured)');
